#pragma once

enum Club {
	ARSENAL = 3,
	BURNLEY = 90,
	BOURNEMOUTH = 91,
	BRIGHTON = 36,
	WEST_HAM = 21,
	CHRYSTAL_PALACE = 31,
	LEICHESTER = 13,
	MAN_CITY = 43,
	MAN_UTD = 1,
	CHELSEA = 8,
	LIVERPOOL = 14,
	NEWCASTLE = 4,
	SOUTHAMPTON = 20,
	TOTTENHAM = 6,
	WATFORD = 57,
	HUDDERSFIELD = 38,
	EVERTON = 11
};

enum Tactics {
	THREE_FIVE_TWO,
	THREE_FOUR_THREE,
	FOUR_FOUR_TWO,
	FOUR_FIVE_ONE,
	FOUR_THREE_THREE,
	FIVE_FOUR_ONE,
	FIVE_THREE_TWO,
	FIVE_TWO_THREE
};